<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ReservationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('reservations')->insert([
            'client' => 'Roberto del Rio',
            'client_email' => 'roberto@prueba.com',
            'room' => 101,
            'date' => Carbon::now()->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 1,
            'number_adults' => 2,
            'number_elders' => 0,
            'total' => 280,
            'total_commission' => 20,
            'actual_pay' => 280,
            'remaining' => 0,
            'status' => 3,
            'confirmed' => true,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 1,
            'tour_id' => 1,
            'hotel_id' => 1,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'María del los Ángeles',
            'client_email' => 'maria@prueba.com',
            'room' => 102,
            'date' => Carbon::now()->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 2,
            'number_adults' => 2,
            'number_elders' => 0,
            'total' => 360,
            'total_commission' => 20,
            'actual_pay' => 300,
            'remaining' => 60,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 1,
            'tour_id' => 1,
            'hotel_id' => 1,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Leonel Migration Busuu',
            'client_email' => 'leonel@prueba.com',
            'room' => 202,
            'date' => Carbon::now()->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 0,
            'number_adults' => 2,
            'number_elders' => 0,
            'total' => 200,
            'total_commission' => 20,
            'actual_pay' => 200,
            'remaining' => 0,
            'status' => 3,
            'confirmed' => true,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 1,
            'tour_id' => 1,
            'hotel_id' => 1,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Andrea Marte',
            'client_email' => 'leonel@prueba.com',
            'room' => 306,
            'date' => Carbon::now()->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 0,
            'number_adults' => 2,
            'number_elders' => 2,
            'total' => 340,
            'total_commission' => 20,
            'actual_pay' => 200,
            'remaining' => 140,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 2,
            'tour_id' => 1,
            'hotel_id' => 4,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Carlos Raul Mauricio',
            'client_email' => 'mauricio@prueba.com',
            'room' => 303,
            'date' => Carbon::now()->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 2,
            'number_adults' => 2,
            'number_elders' => 1,
            'total' => 430,
            'total_commission' => 20,
            'actual_pay' => 360,
            'remaining' => 70,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 1,
            'tour_id' => 1,
            'hotel_id' => 2,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Alejandría de Roma',
            'client_email' => 'alejandria@prueba.com',
            'room' => 512,
            'date' => Carbon::now()->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 1,
            'number_adults' => 2,
            'number_elders' => 2,
            'total' => 300,
            'total_commission' => 20,
            'actual_pay' => 200,
            'remaining' => 100,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 1,
            'tour_id' => 1,
            'hotel_id' => 2,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Roma de Alejandría',
            'client_email' => 'roma@prueba.com',
            'room' => 512,
            'date' => Carbon::now()->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 1,
            'number_adults' => 2,
            'number_elders' => 2,
            'total' => 300,
            'total_commission' => 20,
            'actual_pay' => 200,
            'remaining' => 100,
            'payment_method' => 'efectivo',
            'user_id' => 2,
            'departure_id' => 1,
            'tour_id' => 1,
            'hotel_id' => 2,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Sandy Rubalcaba',
            'client_email' => 'misandria@prueba.com',
            'room' => 512,
            'date' => Carbon::now()->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 1,
            'number_adults' => 2,
            'number_elders' => 2,
            'total' => 300,
            'total_commission' => 20,
            'actual_pay' => 200,
            'remaining' => 100,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 3,
            'tour_id' => 2,
            'hotel_id' => 2,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Hay The Johnes',
            'client_email' => 'haymaker@prueba.com',
            'room' => 462,
            'date' => Carbon::now()->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 2,
            'number_adults' => 2,
            'number_elders' => 0,
            'total' => 160,
            'total_commission' => 20,
            'actual_pay' => 100,
            'remaining' => 60,
            'payment_method' => 'efectivo',
            'user_id' => 2,
            'departure_id' => 1,
            'tour_id' => 1,
            'hotel_id' => 3,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Don Marino',
            'client_email' => 'marino@prueba.com',
            'room' => 232,
            'date' => Carbon::now()->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 1,
            'number_adults' => 2,
            'number_elders' => 1,
            'total' => 250,
            'total_commission' => 35,
            'actual_pay' => 100,
            'remaining' => 60,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 1,
            'tour_id' => 1,
            'hotel_id' => 4,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Rumerio Del Rosario',
            'client_email' => 'rumero@prueba.com',
            'room' => 612,
            'date' => Carbon::now()->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 1,
            'number_adults' => 2,
            'number_elders' => 1,
            'total' => 250,
            'total_commission' => 35,
            'actual_pay' => 100,
            'remaining' => 60,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 3,
            'tour_id' => 2,
            'hotel_id' => 4,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Juan Tenorio',
            'client_email' => 'juan@prueba.com',
            'room' => 793,
            'date' => Carbon::now()->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 1,
            'number_adults' => 2,
            'number_elders' => 1,
            'total' => 250,
            'total_commission' => 35,
            'actual_pay' => 100,
            'remaining' => 60,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 1,
            'tour_id' => 1,
            'hotel_id' => 5,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Genaro Guitierrez',
            'client_email' => 'genaro@prueba.com',
            'room' => 777,
            'date' => Carbon::now()->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 1,
            'number_adults' => 2,
            'number_elders' => 1,
            'total' => 350,
            'total_commission' => 35,
            'actual_pay' => 100,
            'remaining' => 60,
            'payment_method' => 'efectivo',
            'user_id' => 2,
            'departure_id' => 1,
            'tour_id' => 1,
            'hotel_id' => 4,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Hugo del monte',
            'client_email' => 'delmonte@prueba.com',
            'room' => 512,
            'date' => Carbon::now()->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 1,
            'number_adults' => 2,
            'number_elders' => 2,
            'total' => 300,
            'total_commission' => 20,
            'actual_pay' => 200,
            'remaining' => 100,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 3,
            'tour_id' => 2,
            'hotel_id' => 2,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Persona del futuro 1',
            'client_email' => 'futuro@prueba.com',
            'room' => 512,
            'date' => Carbon::now()->addDays(1)->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 1,
            'number_adults' => 2,
            'number_elders' => 2,
            'total' => 300,
            'total_commission' => 20,
            'actual_pay' => 200,
            'remaining' => 100,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 1,
            'tour_id' => 1,
            'hotel_id' => 2,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Persona del futuro 2',
            'client_email' => 'futuro@prueba.com',
            'room' => 512,
            'date' => Carbon::now()->addDays(1)->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 1,
            'number_adults' => 2,
            'number_elders' => 2,
            'total' => 300,
            'total_commission' => 20,
            'actual_pay' => 200,
            'remaining' => 100,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 1,
            'tour_id' => 1,
            'hotel_id' => 2,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Persona del futuro 3',
            'client_email' => 'futuro@prueba.com',
            'room' => 512,
            'date' => Carbon::now()->addDays(1)->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 1,
            'number_adults' => 2,
            'number_elders' => 2,
            'total' => 300,
            'total_commission' => 20,
            'actual_pay' => 200,
            'remaining' => 100,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 1,
            'tour_id' => 1,
            'hotel_id' => 2,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
        DB::table('reservations')->insert([
            'client' => 'Persona del futuro 4',
            'client_email' => 'futuro@prueba.com',
            'room' => 512,
            'date' => Carbon::now()->addDays(1)->toDateString(),
            'telephone' => '0123456789',
            'number_kids' => 1,
            'number_adults' => 2,
            'number_elders' => 2,
            'total' => 250,
            'total_commission' => 20,
            'actual_pay' => 200,
            'remaining' => 100,
            'payment_method' => 'efectivo',
            'user_id' => 1,
            'departure_id' => 1,
            'tour_id' => 1,
            'hotel_id' => 2,
            'folio' => 'TEST003FD',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
    }
}
